const fmtDate = (d) => new Date(d).toLocaleDateString("en-IN");
const fmtAmt = (n) => `Rs. ${Number(n).toLocaleString("en-IN")}`;

// ── CSV / Excel ──────────────────────────────────────────────────────────────
export function downloadCSV(filename, columns, rows) {
  const header = columns.map((c) => `"${c.label}"`).join(",");
  const body = rows.map((row) =>
    columns.map((c) => {
      const val = c.csv ? c.csv(row) : row[c.key] ?? "";
      return `"${String(val).replace(/"/g, '""')}"`;
    }).join(",")
  ).join("\n");

  const blob = new Blob(["\uFEFF" + header + "\n" + body], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ── PDF (browser print) ──────────────────────────────────────────────────────
export function downloadPDF(title, subtitle, columns, rows, summaryRows = []) {
  const tableRows = rows.map((row) =>
    `<tr>${columns.map((c) => `<td>${c.pdf ? c.pdf(row) : row[c.key] ?? ""}</td>`).join("")}</tr>`
  ).join("");

  const summaryHtml = summaryRows.length > 0 ? `
    <table class="summary">
      ${summaryRows.map(([label, value]) => `<tr><td>${label}</td><td>${value}</td></tr>`).join("")}
    </table>` : "";

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"/>
<title>${title}</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:'Segoe UI',Arial,sans-serif;color:#1e293b;padding:36px 40px}
  .header{border-bottom:2px solid #1e293b;padding-bottom:14px;margin-bottom:20px;display:flex;justify-content:space-between;align-items:flex-end}
  .brand{font-size:18px;font-weight:700}
  .brand-sub{font-size:10px;color:#64748b;margin-top:2px}
  .report-title{text-align:right}
  .report-title h2{font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:.5px}
  .report-title p{font-size:10px;color:#64748b;margin-top:3px}
  table{width:100%;border-collapse:collapse;margin-bottom:20px;font-size:12px}
  th{background:#f8fafc;padding:8px 10px;text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#64748b;border-bottom:1px solid #e2e8f0;font-weight:600}
  td{padding:8px 10px;border-bottom:1px solid #f1f5f9;color:#334155}
  table.summary{width:260px;margin-left:auto;margin-bottom:0}
  table.summary td{padding:5px 8px;font-size:12px;border-bottom:1px solid #f1f5f9}
  table.summary td:first-child{color:#64748b}
  table.summary td:last-child{text-align:right;font-weight:600;color:#1e293b}
  .footer{margin-top:28px;padding-top:14px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;font-size:10px;color:#94a3b8}
  @media print{body{padding:24px 28px}.header{border-bottom-color:#000}}
</style></head><body>
<div class="header">
  <div><div class="brand">PaySaathi</div><div class="brand-sub">Billing &amp; Receivables Platform</div></div>
  <div class="report-title"><h2>${title}</h2><p>${subtitle}</p></div>
</div>
<table>
  <thead><tr>${columns.map((c) => `<th>${c.label}</th>`).join("")}</tr></thead>
  <tbody>${tableRows}</tbody>
</table>
${summaryHtml}
<div class="footer">
  <span>Generated by PaySaathi &mdash; ${new Date().toLocaleString("en-IN")}</span>
  <span>Total records: ${rows.length}</span>
</div>
<script>window.onload=()=>{window.print()}<\/script>
</body></html>`;

  const win = window.open("", "_blank", "width=900,height=700");
  win.document.write(html);
  win.document.close();
}

// ── Column definitions per report ────────────────────────────────────────────
export const invoiceColumns = [
  { key: "externalId", label: "Invoice ID", csv: (r) => r.externalId, pdf: (r) => r.externalId },
  { key: "customer",   label: "Customer",   csv: (r) => r.customer,   pdf: (r) => r.customer },
  { key: "amount",     label: "Amount",     csv: (r) => r.amount,     pdf: (r) => fmtAmt(r.amount) },
  { key: "dueDate",    label: "Due Date",   csv: (r) => fmtDate(r.dueDate), pdf: (r) => fmtDate(r.dueDate) },
  { key: "paid",       label: "Paid",       csv: (r) => r.paid,       pdf: (r) => fmtAmt(r.paid) },
  { key: "remaining",  label: "Remaining",  csv: (r) => r.remaining,  pdf: (r) => fmtAmt(r.remaining) },
  { key: "status",     label: "Status",     csv: (r) => r.status,     pdf: (r) => r.status?.toUpperCase() ?? "" },
];

export const overdueColumns = [
  { key: "externalId", label: "Invoice ID", csv: (r) => r.externalId, pdf: (r) => r.externalId },
  { key: "customer",   label: "Customer",   csv: (r) => r.customer,   pdf: (r) => r.customer },
  { key: "amount",     label: "Amount",     csv: (r) => r.amount,     pdf: (r) => fmtAmt(r.amount) },
  { key: "dueDate",    label: "Due Date",   csv: (r) => fmtDate(r.dueDate), pdf: (r) => fmtDate(r.dueDate) },
  { key: "paid",       label: "Paid",       csv: (r) => r.paid,       pdf: (r) => fmtAmt(r.paid) },
  { key: "remaining",  label: "Remaining",  csv: (r) => r.remaining,  pdf: (r) => fmtAmt(r.remaining) },
];

export const customerColumns = [
  { key: "name",               label: "Customer",     csv: (r) => r.name,               pdf: (r) => r.name },
  { key: "email",              label: "Email",        csv: (r) => r.email,              pdf: (r) => r.email },
  { key: "totalInvoiced",      label: "Total Invoiced", csv: (r) => r.totalInvoiced,    pdf: (r) => fmtAmt(r.totalInvoiced) },
  { key: "totalPaid",          label: "Total Paid",   csv: (r) => r.totalPaid,          pdf: (r) => fmtAmt(r.totalPaid) },
  { key: "outstandingBalance", label: "Outstanding",  csv: (r) => r.outstandingBalance, pdf: (r) => fmtAmt(r.outstandingBalance) },
];
